# Generated by Django 3.1.3 on 2020-12-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_book_publisher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not_Read', 'Not Read')], default='Not_Read', max_length=8)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_list', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
