# Generated by Django 3.1.3 on 2020-12-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_publisher_user'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_list', to='books.book', unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='read',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Not_Read', 'Not Read')], default='Not_Read', max_length=8),
        ),
    ]
